# yaml-language-server: $schema=https://reuse.software/reuse-toml-v1.schema.json
version = 1

[[annotations]]
path = [
    "**/*.json",
    "**/*.md",
    "**/.gitignore",
    "go.sum"
]
SPDX-FileCopyrightText = "2025-2026 Andrey Chernykh"
SPDX-License-Identifier = "MIT"
