# SPDX-FileCopyrightText: 2025-2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
name: govulncheck
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '17 3 * * *'
jobs:
  govulncheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-file: go.mod
          output-format: sarif
          output-file: govulncheck.sarif
      - uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4
        with:
          sarif_file: govulncheck.sarif
